definitions:
  v1.VmServiceCheckReq:
    properties:
      services:
        type: string
    type: object
  v1.VmServiceCheckResp:
    properties:
      zdStatus:
        description: Enums consts.HostServiceStatus
        type: string
      zdVersion:
        type: string
      ztfStatus:
        description: Enums consts.HostServiceStatus
        type: string
      ztfVersion:
        type: string
    type: object
  v1.VmServiceInstallReq:
    properties:
      ip:
        description: testing node ip, port ztf:56202, zd:56203
        type: string
      name:
        description: tool name, ztf or zd
        type: string
      secret:
        description: secret to access zentao
        type: string
      server:
        description: zentao server url
        type: string
      version:
        description: tool version
        type: string
    type: object
  v1.VmServiceInstallResp:
    properties:
      version:
        type: string
    type: object
info:
  contact:
    email: 462626@qq.com
    name: API Support
    url: https://github.com/easysoft/zv/issues
  title: ZAgent虚拟机API文档
  version: "1.0"
paths:
  /api/v1/service/check:
    post:
      consumes:
      - application/json
      parameters:
      - description: Service Check Request Object
        in: body
        name: VmServiceCheckReq
        required: true
        schema:
          $ref: '#/definitions/v1.VmServiceCheckReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            $ref: '#/definitions/v1.VmServiceCheckResp'
      summary: 检测虚拟机服务状态
  /api/v1/service/setup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Service Install Request Object
        in: body
        name: VmServiceCheckReq
        required: true
        schema:
          $ref: '#/definitions/v1.VmServiceInstallReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            $ref: '#/definitions/v1.VmServiceInstallResp'
      summary: 安装虚拟机服务
swagger: "2.0"
