definitions:
  _httpUtils.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  domain.Build:
    properties:
      appPath:
        type: string
      appUrl:
        type: string
      appiumPort:
        type: integer
      browserType:
        type: string
      browserVersion:
        type: string
      buildCommands:
        type: string
      buildType:
        type: string
      completeTime:
        type: string
      desc:
        type: string
      deviceIp:
        type: string
      envVars:
        type: string
      id:
        type: integer
      keepResultFiles:
        type: boolean
      name:
        type: string
      nodeIp:
        type: string
      nodePort:
        type: integer
      osCateGory:
        type: string
      osLang:
        type: string
      osType:
        type: string
      osVersion:
        type: string
      priority:
        type: integer
      progress:
        type: string
      projectDir:
        type: string
      queueId:
        type: integer
      resultFiles:
        type: string
      resultMsg:
        type: string
      resultPath:
        type: string
      scmAccount:
        type: string
      scmAddress:
        type: string
      scmPassword:
        type: string
      scriptUrl:
        type: string
      seleniumDriverPath:
        type: string
      serial:
        type: string
      startTime:
        type: string
      status:
        type: string
      testScenario:
        $ref: '#/definitions/domain.TestScenario'
        description: interface test
      testSet:
        $ref: '#/definitions/domain.TestSet'
      version:
        type: number
      vmId:
        type: integer
      workDir:
        type: string
    type: object
  domain.Node:
    properties:
      desc:
        type: string
      ip:
        type: string
      lastRegisterDate:
        type: string
      name:
        type: string
      osPlatform:
        type: string
      osType:
        type: string
      port:
        type: integer
      sshPort:
        type: integer
      sysLang:
        type: string
      version:
        type: number
      vncAddress:
        type: string
      workDir:
        type: string
    type: object
  domain.TestProcessor:
    properties:
      children:
        description: can be interface, Processor.
        items:
          type: object
        type: array
      comments:
        type: string
      dataStore:
        additionalProperties: true
        description: store test data loaded by DataLoopProcessor
        type: object
      default:
        type: string
      endIndex:
        type: integer
      expr:
        type: string
      isOnce:
        type: boolean
      isRand:
        type: boolean
      loop:
        type: integer
      name:
        type: string
      parentId:
        type: integer
      path:
        type: string
      results:
        description: results
        items:
          type: string
        type: array
      source:
        type: string
      src:
        type: string
      startIndex:
        type: integer
      type:
        type: string
      varName:
        type: string
      varNamePostfix:
        type: string
    type: object
  domain.TestScenario:
    properties:
      desc:
        type: string
      name:
        type: string
      processor:
        $ref: '#/definitions/domain.TestProcessor'
      version:
        type: number
    type: object
  domain.TestSet:
    properties:
      agents:
        items:
          $ref: '#/definitions/domain.Node'
        type: array
      desc:
        type: string
      duration:
        description: sec, if set, loopCount will be ignore
        type: integer
      errorAction:
        type: string
      forever:
        type: boolean
      loopCount:
        type: integer
      name:
        type: string
      numberOfThreads:
        type: integer
      processor:
        $ref: '#/definitions/domain.TestProcessor'
      rampUpPeriod:
        description: sec
        type: integer
      version:
        type: number
    type: object
info:
  contact:
    email: 462626@qq.com
    name: API Support
    url: https://github.com/easysoft/zv/issues
  title: ZAgent虚拟机API文档
  version: "1.0"
paths:
  /api/v1/vmware/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Build Request Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/domain.Build'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 创建任务
swagger: "2.0"
