definitions:
  _httpUtils.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  domain.Build:
    properties:
      appPath:
        type: string
      appUrl:
        type: string
      appiumPort:
        type: integer
      browserType:
        type: string
      browserVersion:
        type: string
      buildCommands:
        type: string
      buildType:
        type: string
      completeTime:
        type: string
      desc:
        type: string
      deviceIp:
        type: string
      envVars:
        type: string
      id:
        type: integer
      keepResultFiles:
        type: boolean
      name:
        type: string
      nodeIp:
        type: string
      nodePort:
        type: integer
      osCateGory:
        type: string
      osLang:
        type: string
      osType:
        type: string
      osVersion:
        type: string
      priority:
        type: integer
      progress:
        type: string
      projectDir:
        type: string
      queueId:
        type: integer
      resultFiles:
        type: string
      resultMsg:
        type: string
      resultPath:
        type: string
      scmAccount:
        type: string
      scmAddress:
        type: string
      scmPassword:
        type: string
      scriptUrl:
        type: string
      seleniumDriverPath:
        type: string
      serial:
        type: string
      startTime:
        type: string
      status:
        type: string
      testScenario:
        $ref: '#/definitions/domain.TestScenario'
        description: interface test
      testSet:
        $ref: '#/definitions/domain.TestSet'
      version:
        type: number
      vmId:
        type: integer
      workDir:
        type: string
    type: object
  domain.Node:
    properties:
      desc:
        type: string
      ip:
        type: string
      lastRegisterDate:
        type: string
      name:
        type: string
      osPlatform:
        type: string
      osType:
        type: string
      port:
        type: integer
      sshPort:
        type: integer
      sysLang:
        type: string
      version:
        type: number
      vncAddress:
        type: string
      workDir:
        type: string
    type: object
  domain.TestProcessor:
    properties:
      children:
        description: can be interface, Processor.
        items:
          type: object
        type: array
      comments:
        type: string
      dataStore:
        additionalProperties: true
        description: store test data loaded by DataLoopProcessor
        type: object
      default:
        type: string
      endIndex:
        type: integer
      expr:
        type: string
      isOnce:
        type: boolean
      isRand:
        type: boolean
      loop:
        type: integer
      name:
        type: string
      parentId:
        type: integer
      path:
        type: string
      results:
        description: results
        items:
          type: string
        type: array
      source:
        type: string
      src:
        type: string
      startIndex:
        type: integer
      type:
        type: string
      varName:
        type: string
      varNamePostfix:
        type: string
    type: object
  domain.TestScenario:
    properties:
      desc:
        type: string
      name:
        type: string
      processor:
        $ref: '#/definitions/domain.TestProcessor'
      version:
        type: number
    type: object
  domain.TestSet:
    properties:
      agents:
        items:
          $ref: '#/definitions/domain.Node'
        type: array
      desc:
        type: string
      duration:
        description: sec, if set, loopCount will be ignore
        type: integer
      errorAction:
        type: string
      forever:
        type: boolean
      loopCount:
        type: integer
      name:
        type: string
      numberOfThreads:
        type: integer
      processor:
        $ref: '#/definitions/domain.TestProcessor'
      rampUpPeriod:
        description: sec
        type: integer
      version:
        type: number
    type: object
  v1.KvmReq:
    properties:
      osCategory:
        description: Enums consts.OsCategory
        example: windows
        type: string
      osLang:
        description: Enums consts.OsLang
        example: zh_cn
        type: string
      osType:
        description: Enums consts.OsType
        example: win10
        type: string
      osVersion:
        example: x64-pro
        type: string
      vmBacking:
        type: string
      vmCdromDriver:
        type: string
      vmCdromSys:
        type: string
      vmCpu:
        example: 3
        type: integer
      vmDiskSize:
        example: 30000
        type: integer
      vmMacAddress:
        type: string
      vmMemorySize:
        example: 5120000
        type: integer
      vmTemplate:
        type: string
      vmUniqueName:
        example: test-win10-x64-pro-zh_cn
        type: string
    type: object
  v1.KvmReqClone:
    properties:
      vmCpu:
        example: 3
        type: integer
      vmDiskSize:
        example: 30000
        type: integer
      vmMacAddress:
        type: string
      vmMemorySize:
        example: 5120000
        type: integer
      vmSrc:
        example: test-win10-x64-pro-zh_cn
        type: string
      vmUniqueName:
        example: test-win10-x64-pro-zh_cn-clone1
        type: string
    type: object
  v1.KvmResp:
    properties:
      backingPath:
        type: string
      imagePath:
        type: string
      macAddress:
        type: string
      name:
        type: string
      vncPort:
        type: string
    type: object
  v1.KvmRespTempl:
    properties:
      backingFile:
        type: string
      backingFormat:
        type: string
      cpuCoreNum:
        type: integer
      diskFile:
        type: string
      macAddress:
        type: string
      memoryUnit:
        type: string
      memoryValue:
        type: integer
      name:
        type: string
      osArch:
        type: string
      type:
        type: string
      uuid:
        type: string
    type: object
  v1.MultiPassReq:
    properties:
      cpus:
        type: integer
      disk:
        type: integer
      imgFrom:
        type: string
      imgPath:
        type: string
      password:
        type: string
      userName:
        type: string
      vmMemory:
        type: integer
      vmName:
        type: string
    type: object
  v1.MultiPassResp:
    properties:
      cpus:
        type: string
      image:
        type: string
      ipv4:
        type: string
      memory:
        type: string
      name:
        type: string
      network:
        type: string
      state:
        type: string
    type: object
  v1.VmWareReq:
    properties:
      VmBackingName:
        type: string
      password:
        type: string
      startAfterCreated:
        type: boolean
      userName:
        type: string
      vmId:
        description: for destroy
        type: string
      vmMemory:
        type: integer
      vmName:
        type: string
      vmProcessors:
        type: integer
    type: object
  v1.VmWareResp:
    properties:
      code:
        type: integer
      mac:
        type: string
      msg:
        type: integer
      name:
        type: string
      vmId:
        type: string
      vncAddress:
        type: string
    type: object
info:
  contact:
    email: 462626@qq.com
    name: API Support
    url: https://github.com/easysoft/zv/issues
  title: ZAgent宿主机API文档
  version: "1.0"
paths:
  /api/v1/MultiPass/{name}/reboot:
    post:
      consumes:
      - application/json
      parameters:
      - description: MultiPass Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 重启MultiPass虚拟机
  /api/v1/MultiPass/{name}/resume:
    post:
      consumes:
      - application/json
      parameters:
      - description: MultiPass Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 恢复MultiPass虚拟机
  /api/v1/MultiPass/{name}/suspend:
    post:
      consumes:
      - application/json
      parameters:
      - description: MultiPass Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 暂停MultiPass虚拟机
  /api/v1/MultiPass/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: MultiPass Request Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.MultiPassReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.MultiPassResp'
              type: object
      summary: 创建MultiPass虚拟机
  /api/v1/MultiPass/list:
    post:
      consumes:
      - application/json
      parameters:
      - description: MultiPass Request Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.MultiPassReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.MultiPassResp'
              type: object
      summary: 获取MultiPass虚拟机
  /api/v1/kvm/{name}/destroy:
    post:
      consumes:
      - application/json
      parameters:
      - description: VmWare Request Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.VmWareReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  type: integer
              type: object
      summary: 摧毁VmWare虚拟机
  /api/v1/kvm/{name}/reboot:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 重启KVM虚拟机
  /api/v1/kvm/{name}/resume:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 恢复KVM虚拟机
  /api/v1/kvm/{name}/suspend:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 暂停KVM虚拟机
  /api/v1/kvm/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Request Object
        in: body
        name: kvmReqClone
        required: true
        schema:
          $ref: '#/definitions/v1.KvmReqClone'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.KvmResp'
              type: object
      summary: 克隆KVM虚拟机
  /api/v1/kvm/listTempl:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/v1.KvmRespTempl'
                  type: array
              type: object
      summary: 获取KVM虚拟机模板信息
  /api/v1/multipass/{name}/destroy:
    post:
      consumes:
      - application/json
      parameters:
      - description: MultiPass Request Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.MultiPassReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  type: integer
              type: object
      summary: 摧毁MultiPass虚拟机
  /api/v1/vmware/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: VmWare Request Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.VmWareReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.VmWareResp'
              type: object
      summary: 创建VmWare虚拟机
  /api/v1/vnc/getToken:
    get:
      consumes:
      - application/json
      parameters:
      - description: Vnc Port
        in: query
        name: port
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 根据VNC Port获取Token
swagger: "2.0"
