definitions:
  _domain.Response:
    properties:
      code:
        type: object
      data:
        type: object
      msg:
        type: string
    type: object
  agentModel.Task:
    properties:
      backing:
        type: string
      completionRate:
        type: number
      createdAt:
        type: string
      deleted:
        type: boolean
      deletedAt:
        type: string
      desc:
        type: string
      disabled:
        type: boolean
      endTime:
        type: string
      id:
        type: integer
      md5:
        type: string
      name:
        type: string
      path:
        type: string
      retry:
        type: integer
      startTime:
        type: string
      status:
        type: string
      taskType:
        type: string
      timeoutTime:
        type: string
      updatedAt:
        type: string
      url:
        description: for download
        type: string
      vm:
        description: for export vm
        type: string
      xml:
        type: string
      zentaoTask:
        type: integer
    type: object
  v1.CloneVmReq:
    properties:
      vmCpu:
        example: 3
        type: integer
      vmDiskSize:
        example: 30000
        type: integer
      vmMacAddress:
        type: string
      vmMemorySize:
        example: 5120000
        type: integer
      vmSrc:
        example: test-win10-x64-pro-zh_cn
        type: string
      vmUniqueName:
        example: test-win10-x64-pro-zh_cn-clone1
        type: string
    type: object
  v1.CreateVmReq:
    properties:
      cpu:
        type: integer
      disk:
        type: integer
      memory:
        type: integer
      name:
        type: string
      os:
        description: From 'osinfo-query os' command
        enum:
        - win10
        - ubuntu20.04
        type: string
      path:
        type: string
      taskId:
        type: string
    type: object
  v1.CreateVmResp:
    properties:
      mac:
        type: string
      status:
        description: Enums consts.VmStatus
        type: string
      vnc:
        type: integer
    type: object
  v1.DownloadCancelReq:
    properties:
      url:
        type: string
    type: object
  v1.DownloadReq:
    properties:
      urls:
        items:
          type: string
        type: array
      zentaoTask:
        type: integer
    type: object
  v1.ExportVmReq:
    properties:
      backing:
        type: string
      vm:
        type: string
      zentaoTask:
        type: integer
    type: object
  v1.KvmResp:
    properties:
      agent:
        type: integer
      backing:
        type: string
      image:
        type: string
      ip:
        type: string
      mac:
        type: string
      name:
        type: string
      status:
        description: Enums consts.VmStatus
        type: string
      vnc:
        type: integer
      vncUrl:
        type: string
    type: object
  v1.ListTaskResp:
    properties:
      canceled:
        items:
          $ref: '#/definitions/agentModel.Task'
        type: array
      completed:
        items:
          $ref: '#/definitions/agentModel.Task'
        type: array
      created:
        items:
          $ref: '#/definitions/agentModel.Task'
        type: array
      failed:
        items:
          $ref: '#/definitions/agentModel.Task'
        type: array
      inProgress:
        items:
          $ref: '#/definitions/agentModel.Task'
        type: array
    type: object
  v1.ServiceCheckReq:
    properties:
      services:
        type: string
    type: object
  v1.ServiceCheckResp:
    properties:
      code:
        type: string
      kvm:
        description: Enums consts.HostServiceStatus
        type: string
      novnc:
        description: Enums consts.HostServiceStatus
        type: string
      websockify:
        description: Enums consts.HostServiceStatus
        type: string
    type: object
  v1.VmNotifyReq:
    properties:
      macAddress:
        type: string
    type: object
  v1.VmNotifyResp:
    properties:
      agentPortOnHost:
        type: integer
      ip:
        type: string
      secret:
        type: string
    type: object
  v1.VmPortMapReq:
    properties:
      type:
        description: Enums consts.NatForwardType
        type: string
      vmIp:
        type: string
      vmPort:
        type: integer
    type: object
  v1.VmPortMapResp:
    properties:
      alreadyMapped:
        type: boolean
      hostPort:
        type: integer
      type:
        description: Enums consts.NatForwardType
        type: string
      vmIp:
        type: string
      vmPort:
        type: integer
    type: object
  v1.VncTokenResp:
    properties:
      ip:
        type: string
      port:
        type: string
      token:
        type: string
    type: object
info:
  contact:
    email: 462626@qq.com
    name: Support
    url: https://github.com/easysoft/zv/issues
  title: ZAgent宿主机API文档
  version: "1.0"
paths:
  /api/v1/download/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Download Request Object
        in: body
        name: DownloadReq
        required: true
        schema:
          $ref: '#/definitions/v1.DownloadReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            $ref: '#/definitions/_domain.Response'
      summary: 添加下载任务
  /api/v1/download/cancel:
    post:
      consumes:
      - application/json
      parameters:
      - description: Cancel Download Request Object
        in: body
        name: DownloadCancelReq
        required: true
        schema:
          $ref: '#/definitions/v1.DownloadCancelReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            $ref: '#/definitions/_domain.Response'
      summary: 强制终止下载任务
  /api/v1/kvm/{name}/destroy:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 摧毁KVM虚拟机
  /api/v1/kvm/{name}/reboot:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 重启KVM虚拟机
  /api/v1/kvm/{name}/resume:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 恢复KVM虚拟机
  /api/v1/kvm/{name}/suspend:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 暂停KVM虚拟机
  /api/v1/kvm/clone:
    post:
      consumes:
      - application/json
      parameters:
      - description: Kvm Clone Request Object
        in: body
        name: CloneVmReq
        required: true
        schema:
          $ref: '#/definitions/v1.CloneVmReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.KvmResp'
              type: object
      summary: 克隆KVM虚拟机
  /api/v1/kvm/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Kvm Request Object
        in: body
        name: CreateVmReq
        required: true
        schema:
          $ref: '#/definitions/v1.CreateVmReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.CreateVmResp'
              type: object
      summary: 创建KVM虚拟机
  /api/v1/kvm/exportVm:
    post:
      consumes:
      - application/json
      parameters:
      - description: Export Kvm Request Object
        in: body
        name: ExportVmReq
        required: true
        schema:
          $ref: '#/definitions/v1.ExportVmReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            $ref: '#/definitions/_domain.Response'
      summary: 导出KVM虚拟机为模板镜像
  /api/v1/service/check:
    post:
      consumes:
      - application/json
      parameters:
      - description: Service Check Request Object
        in: body
        name: ServiceCheckReq
        required: true
        schema:
          $ref: '#/definitions/v1.ServiceCheckReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            $ref: '#/definitions/v1.ServiceCheckResp'
      summary: 检测宿主机服务状态
  /api/v1/task/status:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.ListTaskResp'
              type: object
      summary: 获取任务状态
  /api/v1/virtual/addVmPortMap:
    post:
      consumes:
      - application/json
      parameters:
      - description: Vm Port Map Request Object
        in: body
        name: VmPortMapReq
        required: true
        schema:
          $ref: '#/definitions/v1.VmPortMapReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.VmPortMapResp'
              type: object
      summary: 新增虚拟机到宿主机端口的映射
  /api/v1/virtual/getVncToken:
    get:
      consumes:
      - application/json
      parameters:
      - description: VNC Port
        in: query
        name: port
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.VncTokenResp'
              type: object
      summary: 根据VNC Port获取Token
  /api/v1/virtual/notifyHost:
    post:
      consumes:
      - application/json
      parameters:
      - description: Vm Notify Request Object
        in: body
        name: VmNotifyReq
        required: true
        schema:
          $ref: '#/definitions/v1.VmNotifyReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            allOf:
            - $ref: '#/definitions/_domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.VmNotifyResp'
              type: object
      summary: 虚拟机请求安全码
  /api/v1/virtual/removeVmPortMap:
    post:
      consumes:
      - application/json
      parameters:
      - description: Vm Port Map Request Object
        in: body
        name: VmPortMapReq
        required: true
        schema:
          $ref: '#/definitions/v1.VmPortMapReq'
      produces:
      - application/json
      responses:
        "200":
          description: code = success | fail
          schema:
            $ref: '#/definitions/_domain.Response'
      summary: 移除虚拟机到宿主机的端口映射
swagger: "2.0"
