definitions:
  _httpUtils.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  _httpUtils.ResponsePage:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
      pageNo:
        type: integer
      pageSize:
        type: integer
      totalCount:
        type: integer
      totalPage:
        type: integer
    type: object
  domain.BuildHistory:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      nodeIp:
        type: string
      ownerId:
        type: integer
      ownerType:
        type: string
      progress:
        type: string
      queueId:
        type: integer
      resultPath:
        type: string
      status:
        type: string
      vncAddress:
        type: string
    type: object
  model.Environment:
    properties:
      createdAt:
        type: string
      deleted:
        type: boolean
      deletedAt:
        type: string
      disabled:
        type: boolean
      id:
        type: integer
      imageName:
        type: string
      imageSrc:
        type: string
      osCategory:
        example: windows
        type: string
      osLang:
        example: zh_cn
        type: string
      osType:
        example: win10
        type: string
      osVersion:
        type: string
      taskId:
        type: string
      updatedAt:
        type: string
    type: object
  model.Task:
    properties:
      appUrl:
        type: string
      browserType:
        description: Enums consts.BrowserType
        example: chrome
        type: string
      browserVersion:
        type: string
      buildCommands:
        type: string
      buildType:
        description: Enums consts.BuildType
        example: selenium
        type: string
      createdAt:
        type: string
      deleted:
        type: boolean
      deletedAt:
        type: string
      desc:
        type: string
      disabled:
        type: boolean
      endTime:
        type: string
      envVars:
        type: string
      environments:
        description: for selenium test
        items:
          $ref: '#/definitions/model.Environment'
        type: array
      groupId:
        type: integer
      id:
        type: integer
      isDockerNative:
        type: boolean
      keepResultFiles:
        type: boolean
      name:
        type: string
      pendingTime:
        type: string
      priority:
        type: integer
      progress:
        description: Enums consts.BuildProgress
        example: created
        type: string
      resultFiles:
        type: string
      scmAccount:
        type: string
      scmAddress:
        type: string
      scmPassword:
        type: string
      scriptUrl:
        type: string
      serials:
        description: for appium test
        type: string
      startTime:
        type: string
      status:
        description: Enums consts.BuildStatus
        example: pass
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
      userName:
        type: string
    type: object
  v1.Environment:
    properties:
      osCategory:
        example: windows
        type: string
      osLang:
        example: zh_cn
        type: string
      osType:
        example: win10
        type: string
      osVersion:
        type: string
    type: object
  v1.HostRegisterReq:
    properties:
      status:
        description: Enums consts.HostStatus
        example: online
        type: string
      vms:
        items:
          $ref: '#/definitions/v1.VmInHostReq'
        type: array
    type: object
  v1.TaskReq:
    properties:
      appUrl:
        type: string
      browserType:
        description: Enums consts.BrowserType
        example: chrome
        type: string
      browserVersion:
        type: string
      buildCommands:
        type: string
      buildType:
        description: Enums consts.BuildType
        example: selenium
        type: string
      envVars:
        type: string
      environments:
        description: for selenium test
        items:
          $ref: '#/definitions/v1.Environment'
        type: array
      id:
        type: integer
      isDockerNative:
        type: boolean
      keepResultFiles:
        type: boolean
      priority:
        type: integer
      resultFiles:
        type: string
      scmAccount:
        type: string
      scmAddress:
        type: string
      scmPassword:
        type: string
      scriptUrl:
        type: string
      serials:
        description: for appium test
        type: string
    type: object
  v1.TaskResp:
    properties:
      buildHistories:
        items:
          $ref: '#/definitions/domain.BuildHistory'
        type: array
      task:
        $ref: '#/definitions/model.Task'
    type: object
  v1.VmInHostReq:
    properties:
      name:
        type: string
      status:
        description: Enums consts.VmStatus
        example: running
        type: string
    type: object
  v1.VmRegisterReq:
    properties:
      ip:
        type: string
      macAddress:
        example: 1C:1C:1C:24:F4:BF
        type: string
      port:
        example: 8086
        type: integer
      status:
        description: Enums consts.VmStatus
        example: ready
        type: string
      workDir:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/client/host/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Host Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.HostRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 向服务器注册宿主机
  /api/v1/client/task/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Task Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 删除测试任务
    get:
      parameters:
      - description: Task Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.TaskResp'
              type: object
      summary: 获取测试任务
    put:
      consumes:
      - application/json
      parameters:
      - description: Task Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.TaskReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Task'
              type: object
      summary: 更新测试任务
  /api/v1/client/task/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Task Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.TaskReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Task'
              type: object
      summary: 创建测试任务
  /api/v1/client/task/list:
    get:
      parameters:
      - description: 'progress: consts.BuildProgress'
        in: query
        name: progress
        type: string
      - description: 'status: consts.BuildStatus'
        in: query
        name: status
        type: string
      - description: keywords
        in: query
        name: keywords
        type: string
      - description: page no
        in: query
        name: pageNo
        type: integer
      - description: page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            allOf:
            - $ref: '#/definitions/_httpUtils.ResponsePage'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Task'
                  type: array
              type: object
      summary: 列出测试任务
  /api/v1/client/vm/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Vm Object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/v1.VmRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'code = success? 1 : 0'
          schema:
            $ref: '#/definitions/_httpUtils.Response'
      summary: 向服务器注册虚拟机
swagger: "2.0"
